### ISSUE TITLE
Runs only on MAC

### ISSUE THREAD

**Issue by bboerzel** [selfire1/goodsidian#1]
Hi, 
first up, thanks for that script! I already thought about building one like this. 
Sadly the script only runs on a mac. I tried  running it on debian but it seems it can´t handle the variables.
I get this error when I run the script.
```bash
./goodreads-to-obsidian.sh: 44: ./goodreads-to-obsidian.sh: Syntax error: "(" unexpected
```
On my mac it runs without problems.
When I have time, I´ll look into that.
Cheers Ben

**Comment by bboerzel** [comment]
Since I have no rights to push changes to this repo, I forked it with a running version for bash  under linux (tested on ubuntu).
You can find it here and maybe add it in a second branch for the not mac users. ;) 
https://github.com/bboerzel/goodsidian/blob/issue-1/goodreads-to-obsidian.sh

**Comment by selfire1** [comment]
Thanks a lot! I added another branch.
